
# backend: gpu
cost: CrossEntropyBinary
epochs: 10

wt_init: &norm1
    type: Gaussian
    config:
        scale: 0.01
        loc: 0.0

wt_init: &const
    type: Constant
    config:
        val: 0.0

layers:
- type: Linear
  config:
    nout: 100
    init: *norm1
- type: Bias
  config:
    init: *const
- type: Activation
  config:
    transform:
        type: Rectlin
- type: Linear
  config:
    init: *norm1
    name: special_linear
    nout: 10
- type: Bias
  config:
    init: *const
- type: Activation
  config:
    transform:
        type: Logistic
        config:
            shortcut: true


opt_gdm: &gdm
    type: GradientDescentMomentum
    config:
        learning_rate: 0.1
        momentum_coef: 0.9


opt_rms: &rms
    type: RMSProp

optimizer:
    type: MultiOptimizer
    config:
        optimizer_mapping:
            default: *gdm
            special_linear: *rms
            Bias: *rms

dataset:
    name: mnist
